### ISSUE TITLE
Delimiter for export

### ISSUE THREAD

**Issue by pwsandoval** [ethanfurman/dbf#15]
Is there any way to export in csv using a delimiter other than comma? (for example the vertical bar | )

**Comment by wagnerpeer** [comment]
Yes, you can modify the delimiter. If you look at the code, you will find a custom defined dialect named "dbf" for export.
```python
class DbfCsv(csv.Dialect):
    """
    csv format for exporting tables
    """
    delimiter = ','
    doublequote = True
    escapechar = None
    lineterminator = '\n'
    quotechar = '"'
    skipinitialspace = True
    quoting = csv.QUOTE_NONNUMERIC
csv.register_dialect('dbf', DbfCsv)
```

You can inherit and modify the example in your own code and register your new dialect:
```python
class CustomDbfCsv(DbfCsv):
    delimiter = '|'
csv.register_dialect('custom_dbf', CustomDbfCsv)
```

Or you modify the class attribute directly before exporting. But this makes it less obvious.
```python
dbf.DbfCsv.delimiter = '|'
```

**Comment by ethanfurman** [comment]
Thank you for the help, @wagnerpeer !
