### ISSUE TITLE
How to solve this error? Input Chinese character data

### ISSUE THREAD

**Issue by liqi0115** [ethanfurman/dbf#16]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

**Comment by ethanfurman** [comment]
Greetings!  For general help, please ask questions on either Python List or on Stackoverflow.  Github Issues are for problems with the software, not for questions on how to use it.

Python List:  https://mail.python.org/mailman/listinfo/python-list  (sign up for free)
Stackoverflow:  https://stackoverflow.com

When you ask your question make sure to include descriptions of how you are creating/accessing the dbf file, and how you are generating/collecting the data to add to the dbf file.

**Comment by ae86jack** [comment]
I solved this.  When create Table, specify the codepage = 'cp936'
e.g.
`table = dbf.Table(
    filename='test',
    field_specs=field_specs,
    codepage='cp936',
    on_disk=False)`

cp936 defined in __ini__.py,      ` 0x4D : ('cp936', 'Chinese GBK (PRC)')`
