### ISSUE TITLE
Reindex seems not work

### ISSUE THREAD

**Issue by francisps78** [ethanfurman/dbf#2]
Hi all,

Thanks for that package. 
Im using dbf package in python for reading and writing in foxpro dbf files. It runs ok except when I try to update a dbf file with cdx files asociate. After add the new records I use function reindex but it seems not work because if I open the dbf from other application the new records are not available. In order to see the new records I need to open the dbf with microsoft foxpro and puh on reindex. After reindex the new records are available. Please, could you take a look to reindex function? or indicate us how we can reindex the dbf file from python?

Thanks in advance,
Best regards
Fran

**Comment by IvanPagan** [comment]
Hi, then this issue not could be fix never, Is not?

**Comment by ethanfurman** [comment]
This package does not support cdx files at this point.  While I would like to, I don't see myself having enough time to do so.  If you make changes in Python, you'll need to reindex in Foxpro.
