### ISSUE TITLE
Add Latin Codepage? [feature request]

### ISSUE THREAD

**Issue by wolviex** [ethanfurman/dbf#20]
Any interest in adding a latin codepage?
I added latin-1 a.ka. ISO/IEC 8859-1 or cp809 (https://en.wikipedia.org/wiki/ISO/IEC_8859-1)) since I had a number of characters that weren't translating to ascii or utf.
I just stuck it on the end of the end of the code_pages definition:
dbf/__init__.py:8364        0xf1 : ('latin-1', 'Latin Western Europe')

OS: Windows Server 2008 R2
Python 2.7 (I know)

Working for me, happy to submit a pull request: https://github.com/wolviex/dbf
But I also put some comments in the readme regarding Table arguments, and won't take it personally if you'd rather do it differently =)

Thanks!

**Comment by ethanfurman** [comment]
Where did the `0xf1` come from?  Was it a dbf from the Windovs Server environment, or just the next number after my non-standard `0xf0` for unicode?

Except for the unicode option, all the other codes are standard codepage codes for dbf files, and I hesitate to add more codes that only my dbf package (and not other third-party libraries/packages) will be able to read correctly.

**Comment by ethanfurman** [comment]
Does this wikipedia page help?  Did you test all the other codepages to see if any of them matched your text perfectly?

https://en.wikipedia.org/wiki/ISO/IEC_8859-1

**Comment by wolviex** [comment]
I can't say I tested *ALL* of them, but I tested a lot of them. All the 800s, all the 1200s all of the European ones, etc (I thought it was french chars that were messing with me).
Yes, 0xf1 was just the next number after yours.
And latin-1 is a standard encoding in the python library so I don't know how any other package would have an issue..
But this is why i asked :)

**Comment by ethanfurman** [comment]
The 29th byte in a dbf file (counting from zero) is the code-page byte.  All the bytes in the code_pages dictionary, except `\xf0`, have values that should be recognizable by other programs that support the dbf format.

What program did you use to create the dbf file?

**Comment by wolviex** [comment]
I didn't create the dbf, i'm just trying to work with what I have. The software is a dated inventory system specific to my industry that happens to use .dbf database files. 29th byte is \x03 (cp1252), and of course that was one of the first ones I've tried. 

I'll freely admit that my head refuses to wrap around encodings properly and something else could be the issue. 

Just that 'Latin-1' resolved a lot of decode errors for me, it seemed to be a fairly standard CP that a single line of code included as an option. I get what you mean about it not being usual for dbf files though.

**Comment by wolviex** [comment]
More recent changes to the database have rendered this issue moot.  Using cp1252 seems to be working well enough now, so please feel free to disregard the issue. 
Identifying the arguments to dbf.Table is still worth documentation though, IMO.
Thanks for your help!
