### ISSUE TITLE
A bug in __init__.py

### ISSUE THREAD

**Issue by zexiangliu** [ethanfurman/dbf#21]
https://github.com/ethanfurman/dbf/blob/1361d26302f2f943c8409e27ddf9e1af4fb961b2/dbf/__init__.py#L8958-L8959

Line 8959 should be
```
    matches = glob(search_name)
```

**Comment by ethanfurman** [comment]
Thank you.

**Comment by ethanfurman** [comment]
This has been fixed in v0.99.009.
