### ISSUE TITLE
Can you add suport for simplified chinese and traditional chinese word?

### ISSUE THREAD

**Issue by apexbb** [ethanfurman/dbf#28]
Can you add suuport to simplified chinese and traditional chinese word?

**Comment by ethanfurman** [comment]
The dbf format supports codepages for:

- cp936: Chinese GBK (PRC) / Chinese Simplified (PRC, Singapore) Windows
- cp950: Chinese Big 5 (Taiwan) / Traditional Chinese (Hong Kong SAR, Taiwan) Windows

You can set or override the codepage used with:

    dbf.Table(filename, codepage='cp936')
    dbf.Table(filename, codepage='cp950')

**Comment by apexbb** [comment]
HI ,
i am export a dbf from csv,
Do you have function to merge dbf file into dbf file which are both
generated from the from_csv function?
Thanks

Jeff
