### ISSUE TITLE
Incorrect handling of Clipper dbf file with long character field

### ISSUE THREAD

**Issue by bmontana** [ethanfurman/dbf#33]
I'm trying to write Python code to manipulate Clipper dbf tables from an old project of mine. An error is thrown when trying to open one of the files. It has one field (among 38) that is a long character field, with length of 256. Total record length is 629. 

When opening with `dbf_type=None` (the default), I get this error:

`dbf.BadDataError: Header shows record length of 629, but calculated record length is 373`

When opening with `dbf_type='clp'`, it opens properly. However, when accessing `table.current_record`, I get this error:

`dbf.BadDataError: record data is not the correct length (should be 1257, not 629)`

Here is the stack trace:

```
Traceback (most recent call last):
  File "/Users/bill/PycharmProjects/EZ DryClean/src/dbf/taxcalc.py", line 75, in <module>
    main()
  File "/Users/bill/PycharmProjects/EZ DryClean/src/dbf/taxcalc.py", line 21, in main
    dbf_customer.showHead()
  File "/Users/bill/PycharmProjects/EZ DryClean/src/dbf/Clipper.py", line 21, in showHead
    print(self.table.current_record)
  File "/Users/bill/PycharmProjects/EZ DryClean/venv/lib/python3.9/site-packages/dbf/__init__.py", line 2946, in current_record
    return self[index]
  File "/Users/bill/PycharmProjects/EZ DryClean/venv/lib/python3.9/site-packages/dbf/__init__.py", line 5472, in __getitem__
    return self._table[value]
  File "/Users/bill/PycharmProjects/EZ DryClean/venv/lib/python3.9/site-packages/dbf/__init__.py", line 5220, in __getitem__
    maybe = Record(recnum=index, layout=meta, kamikaze=bytes, _fromdisk=True)
  File "/Users/bill/PycharmProjects/EZ DryClean/venv/lib/python3.9/site-packages/dbf/__init__.py", line 3085, in __new__
    raise BadDataError("record data is not the correct length (should be %r, not %r)" %
dbf.BadDataError: record data is not the correct length (should be 1257, not 629)
```

The `showHead()` method referenced above:

```
    def showHead(self, rows: int = 2):
        self.table.goto('top')
        if self.table.bof:
            self.table.skip()
        print(f'Showing {rows} rows for {self.table.filename}')
        print('---------------------------------')
        for i in range(rows):
            print(self.table.current_record)
            self.table.skip()
        print('=================================')
```

The relevant lines from `taxcalc.py`:

```
    dbf_orders = DB('../../data/ORDERS.DBF')
    dbf_orders.showHead()
    dbf_customer = DB('../../data/CUSTOMER.DBF', dbf_type='clp')
    dbf_customer.showHead()
```

`ORDERS.DBF` does not have any long character fields, and everything works properly for it. `CUSTOMER.DBF` has the one long character field (256).

I've been trying to find the bug and fix it, but haven't been able to isolate it, yet.

**Comment by bmontana** [comment]
I'm using the version installed with pip: 0, 99, 2. I see that the version on GitHub is 0, 99, 3, 1. Should I try that first?

I made a copy of `CUSTOMER.DBF`, and confirmed the same error with the copy.

[CUSTCOPY.DBF.zip](https://github.com/ethanfurman/dbf/files/10306219/CUSTCOPY.DBF.zip)

**Comment by ethanfurman** [comment]
Verified error still exists.  Working on it.

**Comment by bmontana** [comment]
I'm testing with `TOTALS.DBF` and `CUSTOMER.DBF`. 

There seems to be a discrepancy at `dbf.Table` object instantiation, in `Record » _create_blank_data()`,  after the statement `layout.blankrecord = record._data[:]`. `TOTALS.DBF` is a `Db3Table`, whereas, `CUSTOMER.DBF` is a `ClpTable`. 

Results for the two tables are outlined in this table...

```
Variable/value                TOTALS.DBF   CUSTOMER.DBF
--------------                ----------   -----------------
actual record length          329           629
len(layout.blankrecord)       329          1257
layout.header.record_length   329           629
```

When accessing `table.current_record` in `showHead()` method, at assignment `maybe = Record(...)` in `Table » _Table » __getitem__()`...
```
Variable/value              TOTALS.DBF   CUSTOMER.DBF
--------------              ----------   -----------------
len(meta.blankrecord)       329          1257
meta.header.record_length   329           629
```

An error is raised in `Record » __new__()` because `len(record._data) != len(kamikaze)`. Those lengths are `1257` and `629`, respectively.


Taking a deeper dive...

during instantiation...
before `Record._create_blank_data(meta)` in `ClpTable » _initialize_fields()`...
`meta.blankrecord` is blank
`len(meta.header.data) = 1250`
`meta.header.record_length = 629`
`offset = 629`
`total_length = 629`

stepping into `Record._create_blank_data(meta)`...
parameter `layout`...
`blankrecord` is blank
`len(header.data) = 1250`
`header.record_length = 629`

`record` object is created and some protected attributes are assigned. `record._data` is assigned, using `layout.header.record_length`, and therefore has the correct length (for now). However, by the time `layout.blankrecord` is assigned, near the end of the method, the length of `record._data` is `1257`.

POSSIBLE PROBLEM LOCATION?
Something unexpected seems to be happening in the `for` loop containing `if name != '_NULLFLAGS':`. However, this is still in `Table` object instantiation, which seems to work fine.

Back in `Table » __init__()`, after calling `self._initialize_fields()`, `len(meta.blankrecord) = 1257`, and `meta.header.record_length = 629`.

Now, on to `table.open()`...
Upon entry, `self.record_length = 629`.
`len(self._meta.blankrecord) = 1257`
`self._meta.header.record_length = 629`


I got your message while working on this. I'm going to stop this run, and focus on that `for` loop in more detail. It seems that `blankrecord` is being set to roughly double the proper length.

Thanks,
Bill

**Comment by bmontana** [comment]
In `Record » _create_blank_data() » for index, name in enumerate(layout.fields): » if name != '_NULLFLAGS':`...

I noticed the `start` and `end` values for a `ClpTable` are HUGE integers. They are being used in the statement `record._data[start:end] = array('B', blank(size))`. Those values are 'normal' for `Db3Table`. Is it possible that the array is being tacked on to the end, instead of some preferred behavior? Forgive my ignorance of the intricacies of dbf table formats.

–Bill

**Comment by ethanfurman** [comment]
Those huge values are the problem, but they come from the file itself -- which is to say. the header of the clp file is not being created correctly.

**Comment by bmontana** [comment]
Interesting! These tables are created and maintained by Clipper code. I wonder if big numbers are normal for Clipper files, and hold additional info (needing to be decoded). Or are the start and end values stored elsewhere in a Clipper dbf header? Shouldn't be. 

Where in `__init__.py` are they being read?

**Comment by ethanfurman** [comment]
That is interesting.  If you create a Clipper table with no large Character fields, do you still have the problem?

The header is parsed in `ClpTable._initialize_fields`.

**Comment by bmontana** [comment]
My Clipper books are packed in a box somewhere, and I haven't been able to find Clipper-specific file format info online. Do you have a source?

**Comment by bmontana** [comment]
> That is interesting. If you create a Clipper table with no large Character fields, do you still have the problem?
> 
> The header is parsed in `ClpTable._initialize_fields`.

No, all is well when large Character fields are not used. All tables I use are Clipper tables, but open as `Db3Table` objects in `dbf` when there are not large Character fields.

**Comment by ethanfurman** [comment]
Can't find mine at the moment, but the general header format for `dbf` can be [found here](https://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_STRUCT).

**Comment by bmontana** [comment]
That's much better than the one I've been using. Thanks!

**Comment by ethanfurman** [comment]
I'm testing a fix now.

**Comment by bmontana** [comment]
I'm sure you noticed that the field data address is the same for every field (14 A1 61 6F). Interestingly, it's the same in `TOTALS.DBF` (but not for all other dbf files I have). So, some calculation is being done to arrive at the offset to the first field location (???). Field lengths are correct, and undoubtedly figure in to the calculation.

**Comment by ethanfurman** [comment]
The first field always starts at offset `1` (offset `0` is the deleted flag).

**Comment by bmontana** [comment]
Yes, within each record. I was referring to the field data address in the field descriptor array (in the spec). That is what's being read to arrive at the `start` value, correct?

**Comment by ethanfurman** [comment]
Ah, yes.  The first 32 bytes is the file header, then a succession of 32-byte chunks (one for each field), and the start location is at offset 12-15.

New version is uploaded, although `pip` may not see it for a couple minutes.

**Comment by bmontana** [comment]
Thank you so much! Looks good so far!
