### ISSUE TITLE
How can i delete a row in a Visual Fox Pro Table? 

### ISSUE THREAD

**Issue by AldoSoto3003** [ethanfurman/dbf#37]
i tried with Db.delete_fields(), but i dont know how to use it.

thanks

**Comment by ethanfurman** [comment]
Hello!  These issues are a place to file bugs, not ask for help.

Here are some SO answers that may offer clues:

- https://stackoverflow.com/questions/48832107/
- https://stackoverflow.com/questions/26532138/

And the search I used:

- https://stackoverflow.com/search?q=user%3A208880+dbf+delete+

Please ask a new question there if you still need help.

Thanks!
