### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by juzj** [ethanfurman/dbf#38]
Is it documented? Read and write operations

**Comment by turicas** [comment]
I'm not sure if it's still maintained, but I'm using this library in a project.
For docs, you can check the [README.md inside `dbf` folder](https://github.com/ethanfurman/dbf/blob/master/dbf/README.md) and also [my pull request adding an example on how to read DBFs](https://github.com/ethanfurman/dbf/pull/41).

**Comment by ethanfurman** [comment]
Yes, it is maintained.  Yes, the docs are mostly inadequate.

**Comment by muratcansarkalkan** [comment]
So I saw this through looking at pull requests. Sure, reading through issues and pull requests should be a skill for a developer is important, but it would also be great to have this at the README.md file.
