### ISSUE TITLE
Method "delete_record" does not exist 

### ISSUE THREAD

**Issue by SThomasN** [ethanfurman/dbf#39]
https://github.com/ethanfurman/dbf/blob/4f8ff35bec18ca167981ba741bfe353f5f362f99/dbf/__init__.py#L8392-L8393

These methods do not appear to exist.

Perhaps the delete_record() method could be replaced with delete() function?

**Comment by ethanfurman** [comment]
Thanks for the report!  Should be fixed in v0.99.009.
