### ISSUE TITLE
Problem Creating a DBF with an Integer Field

### ISSUE THREAD

**Issue by jastoneii** [ethanfurman/dbf#45]
Hi,
I wrote the following routine to create a new DBF file from an existing structure extended DBF file.

```python
def create_dbf_from(struct_file, new_file):
  db = dbf.Table(struct_file)
  db.open(mode=dbf.READ_ONLY)
  structure_str = ""
  reccount = 0
  for record in db:
    if reccount > 0:
      structure_str += "; " + record.field_name.rstrip()
      reccount += 1
    else:
      structure_str += record.field_name.rstrip()
      reccount = 1
    if record.field_type == "N" or record.field_type == "B"  or record.field_type == "F":
       structure_str += " "+record.field_type+"("+str(record.field_len)+","+str(record.field_dec)+")"
    else:
       if record.field_type != "C":
         structure_str += " "+record.field_type
       else:
         structure_str += " "+record.field_type+"("+str(record.field_len)+")"

  db.close()
  print(structure_str)
  newdb = dbf.Table(new_file, structure_str)
  newdb.close()
```

It works except when the structure extended file contains an Integer field. I then tried just entering the following commands into Python:
import DBF
new_table = dbf.Table('new_file_name.dbf', 'field1 I; field2 N(5,2)')

I get the following error message:
  File C:\ProgramData\anaconda3\lib\site-packages\dbf\__init__.py:5585 in __init__
    self.add_fields(field_specs)

  File C:\ProgramData\anaconda3\lib\site-packages\dbf\__init__.py:5888 in add_fields
    raise FieldSpecError("Unknown field type:  %s" % field_type)

FieldSpecError: Unknown field type:  FieldType.INTEGER

Is it something that I am doing or does "dbf" have an issue creating an integer field.

TIA,

Jeff

**Comment by ethanfurman** [comment]
To get the structure of a table you can do:

```python
db = dbf.Table('some_file.dbf')
structure = db.structure()
```

The default table type is dbase III (db3), which does not support Integer fields, only Numeric.  In this library, only vfp tables support Integer fields.  To find the table type of db:

```python
dbf.table_type(db)
```

**Comment by jastoneii** [comment]
Hi Ethan,

Thanks for the reply.  VFP has structure extended files which are DBF files with the fields: Field_Name, Field_Len, Field_Dec, etc that contain the structure of a DBF file that you can create by executing the command:
     create newfile from structure_extendeddbf 
We are just trying to replicate VFP functionality.  For anyone who cares, a working Python equivalent create function is:

def create_dbf_from(struct_file, new_file):
  db = dbf.Table(struct_file)
  db.open(mode=dbf.READ_ONLY)
  structure_str = ""
  reccount = 0
  for record in db:
    if reccount > 0:
      structure_str += "; " + record.field_name.rstrip()
      reccount += 1
    else:
      structure_str += record.field_name.rstrip()
      reccount = 1
    if record.field_type == "N":
       structure_str += " "+record.field_type+"("+str(record.field_len)+","+str(record.field_dec)+")"
    else:
       if record.field_type != "C":
         structure_str += " "+record.field_type
       else:
         structure_str += " "+record.field_type+"("+str(record.field_len)+")"

  db.close()
  print(structure_str)
  newdb = dbf.Table(new_file, structure_str, dbf_type='vfp')
  newdb.close()

**Comment by ethanfurman** [comment]
Glad you got it figured out.
