### ISSUE TITLE
Is there any plan to license this repository?

### ISSUE THREAD

**Issue by cmsax** [ethanfurman/dbf#5]
[GitHub: Add a license to a repository](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

[which open source license is appropriate for my project](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project)

By default, if no license is provided, we can just view the source code but cannot use it for commercial purpose nor change, merge, distribute, sub license, etc.

Please license this repository so that people can determine whether to use this awesome project or not in their own projects.

**Comment by ethanfurman** [comment]
The license is in the dbf folder.  I have it there so it gets installed when `pip` is used.  If you know how to have it be in the root of the repository and be installed in the package, feel free to provide a patch.  :-)

**Comment by cmsax** [comment]
Oh! It's there, I'll try! Thanks! 👍
