### ISSUE TITLE
DeprecationWarning importing ABCs from collections

### ISSUE THREAD

**Issue by thomasschus** [ethanfurman/dbf#9]
I'm currently using dbf with Python 3.8 when I received this warning:
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working`
Are there plans to adopt for Python 3.9?

**Comment by tirkarthi** [comment]
I have created https://github.com/ethanfurman/dbf/pull/10 as a potential fix.
